version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:8001
        volumes:
            - .:/var/www/html
        depends_on:
            - database
    database:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: mcca
            # MYSQL_USER: root
            # MYSQL_PASSWORD:
            # MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
